-- 평균 일일 대여 요금 구하기

-- CREATE TABLE 
CREATE TABLE CAR_RENTAL_COMPANY_CAR (
	CAR_ID INTEGER NOT NULL,
	CAR_TYPE VARCHAR(255) NOT NULL,
	DAILY_FEE INTEGER NOT NULL,
	OPTIONS VARCHAR(255) NOT NULL
);

-- INSERT DATA
INSERT INTO CAR_RENTAL_COMPANY_CAR (CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS)
VALUES (1, '세단', 16000, '가죽시트,열선시트,후방카메라');
INSERT INTO CAR_RENTAL_COMPANY_CAR (CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS)
VALUES (2, 'SUV', 14000, '스마트키,네비게이션,열선시트');
INSERT INTO CAR_RENTAL_COMPANY_CAR (CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS)
VALUES (3, 'SUV', 22000, '주차감지센서,후방카메라,가죽시트');

COMMIT;

-- SELECT 문제
/*
 * CAR_RENTAL_COMPANY_CAR 테이블에서 자동차 종류가 
 * 'SUV'인 자동차들의 평균 일일 대여 요금을 출력하는 SQL문을 작성해주세요. 
 * 이때 평균 일일 대여 요금은 소수 첫 번째 자리에서 반올림하고, 
 * 컬럼명은 AVERAGE_FEE 로 지정해주세요.
 * */

SELECT AVG(DAILY_FEE) AS AVERAGE_FEE FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE LIKE 'SUV';