-- 인기있는 아이스크림

-- CREATE TABLE

CREATE TABLE FIRST_HALF (
	SHIPMENT_ID	NUMBER NOT NULL,
	FLAVOR VARCHAR2(100) NOT NULL,
	TOTAL_ORDER NUMBER NOT NULL
);

-- INSERT DATA

INSERT INTO FIRST_HALF(SHIPMENT_ID, FLAVOR, TOTAL_ORDER)
VALUES ('101','chocolate',3200);
INSERT INTO FIRST_HALF(SHIPMENT_ID, FLAVOR, TOTAL_ORDER)
VALUES ('102','vanilla',2800);
INSERT INTO FIRST_HALF(SHIPMENT_ID, FLAVOR, TOTAL_ORDER)
VALUES ('103','mint_chocolate',1700);
INSERT INTO FIRST_HALF(SHIPMENT_ID, FLAVOR, TOTAL_ORDER)
VALUES ('104','caramel',2600);
INSERT INTO FIRST_HALF(SHIPMENT_ID, FLAVOR, TOTAL_ORDER)
VALUES ('105','white_chocolate',3100);
INSERT INTO FIRST_HALF(SHIPMENT_ID, FLAVOR, TOTAL_ORDER)
VALUES ('106','peach',2450);
INSERT INTO FIRST_HALF(SHIPMENT_ID, FLAVOR, TOTAL_ORDER)
VALUES ('107','watermelon',2150);
INSERT INTO FIRST_HALF(SHIPMENT_ID, FLAVOR, TOTAL_ORDER)
VALUES ('108','mango',2900);
INSERT INTO FIRST_HALF(SHIPMENT_ID, FLAVOR, TOTAL_ORDER)
VALUES ('109','strawberry',3100);
INSERT INTO FIRST_HALF(SHIPMENT_ID, FLAVOR, TOTAL_ORDER)
VALUES ('110','melon',3150);
INSERT INTO FIRST_HALF(SHIPMENT_ID, FLAVOR, TOTAL_ORDER)
VALUES ('111','orange',2900);
INSERT INTO FIRST_HALF(SHIPMENT_ID, FLAVOR, TOTAL_ORDER)
VALUES ('112','pineapple',2900);

-- SELECT 문제

/*
 * 상반기에 판매된 아이스크림의 맛을 총주문량을 
 * 기준으로 내림차순 정렬하고 
 * 총주문량이 같다면 출하 번호를 기준으로 오름차순 정렬하여 조회하는 SQL 문을 작성해주세요.
 * */

SELECT FLAVOR
FROM FIRST_HALF
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC;