-- 3월에 태어난 여성 회원 목록 출력하기

-- CREATE TABLE

CREATE TABLE MEMBER_PROFILE(
	MEMBER_ID VARCHAR(100) NOT NULL,
	MEMBER_NAME	VARCHAR(50)	NOT NULL,
	TLNO VARCHAR(50),
	GENDER VARCHAR(1),
	DATE_OF_BIRTH DATE
);

-- INSERT DATA

INSERT INTO MEMBER_PROFILE(MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH)
VALUES('jiho92@naver.com','이지호','01076432111','W','1992-02-12');
INSERT INTO MEMBER_PROFILE(MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH)
VALUES('jiyoon22@hotmail.com','김지윤','01032324117','W','1992-02-22');
INSERT INTO MEMBER_PROFILE(MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH)
VALUES('jihoon93@hanmail.net','김지훈','01023258688','M','1993-02-23');
INSERT INTO MEMBER_PROFILE(MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH)
VALUES('seoyeons@naver.com','박서연','01076482209','W','1993-03-16');
INSERT INTO MEMBER_PROFILE(MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH)
VALUES('yoonsy94@gmail.com','윤서연',NULL,'W','1994-03-19');

-- SELECT 문제 
/*
 * MEMBER_PROFILE 테이블에서 
 * 생일이 3월인 여성 회원의 ID, 이름, 성별, 생년월일을 조회하는 SQL문을 작성해주세요. 
 * 이때 전화번호가 NULL인 경우는 출력대상에서 제외시켜 주시고, 
 * 결과는 회원ID를 기준으로 오름차순 정렬해주세요.
 * */

SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH,'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TO_CHAR(DATE_OF_BIRTH, 'MM') LIKE '03'
AND TLNO IS NOT NULL
AND GENDER = 'W'
ORDER BY MEMBER_ID ASC;